r"""Body copy for the technical dossier page. Built by viz/build_artifacts.py.

Kept in its own module because the page is long and the builder should stay readable.
Nothing here computes anything - every number is a measured result recorded in the branch
README, and every figure is generated by another script in this folder.

SCOPE, versus the brief:
  * the brief carries +20 deg only; this page carries BOTH angles, each with its own section,
    because the second angle is what turns a result into a finding.
  * deeper on method - meshing, validation and the imaging chain get their own treatment.
  * every annotated comparison still ships with its un-annotated twin.
  * current state only. No account of superseded configurations - that history lives in git
    and in the branch README, not in a document someone reads to decide something.
"""
from __future__ import annotations


def body(img: dict, c5) -> str:
    """img maps short keys to data URIs; c5 carries the crack-fill experiment result."""
    return f"""
<header class="mast">
  <p class="eyebrow">DarkVision R&amp;D &middot; branch rnd-nima-fea &middot; technical dossier</p>
  <h1>Simulating a crack in a pipe wall, twice, and finding out which answer to trust</h1>
  <p class="lede col">An open-source finite-element ultrasound simulation, benchmarked
  head-to-head against the research team's MATLAB k-Wave model, on their scenario, through
  their own imaging code. This is the long version: the physics, the method, both steering
  angles, every number, and every claim we could not support.</p>
</header>

<div class="verdict good col">
  <span class="kicker">The short version</span>
  <p>At both usable steering angles our simulation <strong>separates the crack from background
  clutter better than k-Wave</strong> &mdash; <span class="n">+2.5</span> and
  <span class="n">+1.8</span> dB, unanimous across every analysis choice tested &mdash; and
  locates it to well under half their error. On <em>sizing</em> we are better at
  <span class="n">+20&deg;</span> (<span class="n">&minus;6.8%</span> against their
  <span class="n">&minus;13%</span>) and exactly tied at <span class="n">&minus;20&deg;</span>.
  Across all thirty robustness checks we are closer to truth in <span class="n">25</span>.</p>
  <p>The underlying physics is validated against exact analytical solutions to about
  <span class="n">1%</span>, with no fitted parameters. Two bounds up front: the contrast
  advantage is a <em>floor</em>, not a converged value, and <strong>why</strong> we measure
  better is still open &mdash; both obvious explanations were tested inside our own solver and
  eliminated.</p>
</div>

<h2 class="col"><span class="num">01</span>What the inspection actually has to do</h2>
<div class="col">
<p>An in-line inspection tool travels inside a pipeline and has to find cracks in the wall
from the inside, swimming in fluid, without touching anything. The specific target here is a
steel pipe with a <span class="n">9.525</span> mm wall &mdash; <span class="n">387.35</span> mm
inner diameter, <span class="n">406.40</span> mm outer &mdash; carrying a notch cut into its
<em>outer</em> surface, <span class="n">4.0</span> mm deep and <span class="n">1.0</span> mm
wide. That is <span class="n">42%</span> through-wall, on the far side of the wall, viewed
from <span class="n">20</span> mm away through water.</p>
<p>The instrument is a <strong>256-element phased array</strong> on a
<span class="n">0.30</span> mm pitch firing a <strong>single cycle</strong> of
<span class="n">4</span> MHz. The single cycle matters: a short pulse is what makes echoes
separable in time, and time is what this measurement is made of.</p>
<h3>The answer is a time, not a brightness</h3>
<p>The tool does not photograph the crack. It measures <em>when</em> echoes return and infers
geometry from arrival times. Get an amplitude 20% wrong and the picture is dimmer. Get a time
wrong by a fraction of a microsecond and the crack appears where it is not, or its depth is
misread. Every numerical choice in this project follows from that asymmetry:
<strong>timing matters far more than amplitude</strong>.</p>
</div>

<h2 class="col"><span class="num">02</span>Why the beam is steered, and what "TT-T" means</h2>
<div class="col">
<p>Fired straight at the wall, a narrow notch is nearly invisible &mdash; it presents almost
no surface back towards the array, and its echo is buried under the much louder front-wall
reflection. So the array steers to <span class="n">20&deg;</span>, and something useful happens
at the water/steel interface.</p>
<p>Steel carries two wave types: <strong>compression</strong> (particles move along the
direction of travel, <span class="n">5700</span> m/s) and <strong>shear</strong> (across it,
<span class="n">3100</span> m/s). Water carries only compression, because it has no shear
stiffness. At an angle, an incoming compression wave converts into <em>both</em> inside the
steel, in proportions set by the angle. That is <em>mode conversion</em>.</p>
<p>At <span class="n">20&deg;</span> it is exploited deliberately. Snell's law puts the
critical angle for compression at <span class="n">15.3&deg;</span>, so beyond that it cannot
propagate into the steel at all &mdash; it becomes evanescent and dies within a fraction of a
millimetre of the surface. What survives is an almost <strong>pure shear wave at about
45&deg;</strong>, which travels down through the wall, reflects off the outer surface, and
illuminates the notch from the side. That is the geometry a surface-breaking crack presents
best.</p>
<p><code>TT-T</code> names that path, and the naming convention is worth knowing: letters
before the dash are the transmit legs, after it the receive legs, <code>T</code> for transverse
(shear) and <code>L</code> for longitudinal (compression). So <code>TT-T</code> is two shear
legs out via a half-skip off the outer wall, and one shear leg back. The recipe also applies a
<span class="n">60&deg;/80&deg;</span> angle filter, which <code>TT</code> and <code>LL</code>
do not.</p>
<p>It is also why <span class="n">0&deg;</span> is excluded from every comparison here &mdash;
at normal incidence there is no mode conversion, so the wave the imaging code looks for was
never launched, and <em>both</em> solvers produce meaningless images. That is a property of the
method, not a limitation of either model.</p>
</div>

<figure>
  <img src="{img['gif']}" alt="Animated wavefield: the steered beam converting to shear">
  <figcaption><b>The mechanism, in our simulation.</b> Water carries no shear, so the two wave
  types can be shown together without ambiguity: compression (<code>div u</code>) in the water,
  shear (<code>curl u</code>) in the steel. The steered wavefront sweeps in, converts at the
  inner wall, and the shear wave zig-zags through the wall on the half-skip path toward the
  notch at <span class="n">x = 38.25</span> mm. Illustrative resolution; every quoted number
  comes from the higher-resolution runs.</figcaption>
</figure>
<figure>
  <img src="{img['wave_late']}" alt="Wavefield snapshot at 31 microseconds">
  <figcaption><b>One frame, held still, at <span class="n">31</span> &micro;s.</b> Worth
  studying rather than watching: the compression wave is confined to the water, the steel
  carries shear only, the wavefront inside the wall runs at roughly
  <span class="n">45&deg;</span> as Snell requires, and the scattered lobes from the notch tip
  are already separating from the outer-wall reflection. Nothing in this picture was
  prescribed &mdash; mode conversion, the refraction angle and the scattering all emerge from
  one equation and the geometry.</figcaption>
</figure>

<h2 class="col"><span class="num">03</span>Two ways to simulate a wave</h2>
<div class="col">
<p>Both models solve the same elastic wave equation &mdash; Newton's second law for a
continuous solid closed with Hooke's law. They disagree about how to represent <em>space</em>,
and that is the whole story.</p>
</div>
<div class="eq col">
&rho;&nbsp;&part;<sup>2</sup><b>u</b>/&part;t<sup>2</sup> = &nabla;&sdot;&sigma;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&sigma; = &lambda;(&nabla;&sdot;<b>u</b>)<b>I</b> + 2&mu;&nbsp;&epsilon;(<b>u</b>)
<span class="lbl">one equation, both wave types, both materials</span>
</div>
<div class="col">
<p>The two wave speeds are consequences, not inputs:
<span class="n">c<sub>P</sub></span> = &radic;((&lambda;+2&mu;)/&rho;) and
<span class="n">c<sub>S</sub></span> = &radic;(&mu;/&rho;). Water is the <em>same</em> equation
with <span class="n">&mu; = 0</span>, which is why a single monolithic displacement field
covers water and steel with no explicit coupling condition: continuity of traction and
displacement at the interface falls out of the weak form automatically. The sensors record
pressure, which in that formulation is
<span class="n">p = &minus;&lambda;<sub>water</sub>&nbsp;&nabla;&sdot;<b>u</b></span>.</p>
<h3>k-Wave: a uniform grid</h3>
<p>k-Wave is <strong>pseudospectral</strong> on a uniform Cartesian grid &mdash;
<span class="n">50</span> &micro;m squares here. In smooth material it is genuinely excellent:
derivatives come from Fourier transforms, which is spectrally accurate and needs only about two
points per wavelength, far fewer than finite elements. <strong>We do not dispute that.</strong>
The cost is that geometry has to be painted onto that grid. A curved wall becomes a
<strong>staircase</strong>; a crack becomes a block of pixels. And because a grid cannot contain
a hole, the crack must be filled with <em>something</em> &mdash; k-Wave fills it with a
fictitious solid at <span class="n">500</span> m/s, which at 4 MHz is only about
<span class="n">2.5</span> points per wavelength.</p>
<p>In fairness to their implementation, it does not crudely staircase: it blends material
properties across a <span class="n">&plusmn;62.5</span> &micro;m band to give sub-pixel
interfaces. It is a careful use of the method, not a naive one.</p>
<h3>FEniCS/DOLFINx: a mesh that follows the geometry</h3>
<p>We use <strong>spectral elements</strong> &mdash; finite elements with high-order
polynomials inside each cell &mdash; on a mesh of <span class="n">45,711</span> quadrilaterals
whose edges lie <em>on</em> the true geometry. The pipe surfaces are meshed as exact circular
arcs, and the notch is cut as real geometry: a true void whose faces are mesh boundaries. A
void needs no fake material, because the natural boundary condition of the equations on a free
surface is exactly traction-free, which is what steel against air is.</p>
<p>Measured, the fidelity gap is large. Our meshed arcs deviate from the true circle by
<strong><span class="n">0.05</span> &micro;m</strong>, against roughly
<span class="n">140</span> &micro;m for a staircase at the same cell size &mdash; a factor of
about <span class="n">700</span>. Whether that fidelity is <em>why</em> we win is a separate
question, and section 12 answers it uncomfortably.</p>
</div>

<figure>
  <img src="{img['mesh']}" alt="Mesh zooms: conforming arc, 50 micron staircase, notch tip">
  <figcaption><b>What "conforming" means, drawn from the real meshes.</b> Blue is the interface
  the mesh actually has; dashed green is the exact circle. Panels 2 and 3 use the <em>same</em>
  window, deliberately off-axis where the wall is steep &mdash; at the arc's apex a
  <span class="n">50</span> &micro;m staircase runs flat for <span class="n">&plusmn;3.1</span>
  mm and would look harmless, which is exactly the trap in judging this by eye at the centre.
  Panel 4 is the notch tip: a real void with exact corners.</figcaption>
</figure>

<h2 class="col"><span class="num">04</span>Meshing: how the cell size is actually chosen</h2>
<div class="col">
<p>This is the part a grid method cannot do, so it is worth being precise about. The mesh is
deliberately <strong>non-uniform</strong>, and the sizes are derived from the wavelength rather
than chosen by feel. With a target of <span class="n">N</span> nodes per wavelength and a
degree-<span class="n">p</span> element carrying <span class="n">p</span> node spacings across
a cell, the requirement is:</p>
</div>
<div class="eq col">
h &asymp; p&nbsp;&lambda;<sub>min</sub> / N &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lambda; = c / f
<span class="lbl">cell size follows the shortest wavelength present</span>
</div>
<div class="tw">
<table>
<caption>Target cell sizes before the global <code>--scale</code> multiplier. Production runs
<code>--scale 0.8</code>, so every value shrinks by a fifth.</caption>
<thead><tr><th>Region</th><th class="num">h [mm]</th><th>What sets it</th></tr></thead>
<tbody>
<tr><td class="row-label">Water</td><td class="num">0.28</td>
  <td><span class="n">3&thinsp;&times;&thinsp;&lambda;/4</span> with
  <span class="n">&lambda; = 1500/4</span> MHz <span class="n">= 0.375</span> mm</td></tr>
<tr><td class="row-label">Steel</td><td class="num">0.56</td>
  <td>2&times; water, because the shear wavelength <span class="n">0.775</span> mm is about
  twice the water one</td></tr>
<tr><td class="row-label">Notch faces and tip</td><td class="num">0.30</td>
  <td><b>not</b> wavelength &mdash; deliberately coarse, see below</td></tr>
<tr><td class="row-label">Array face</td><td class="num">0.09</td>
  <td><b>not</b> wavelength &mdash; must resolve individual transducer elements</td></tr>
</tbody>
</table>
</div>
<div class="col">
<p><strong>The slowest material needs the finest cells.</strong> Because
<span class="n">&lambda; = c/f</span>, water at <span class="n">1500</span> m/s has a shorter
wavelength than steel at <span class="n">3100</span>, so the water gap is meshed finer than the
steel wall &mdash; even though the crack we are hunting is in the steel. The size callback
never relaxes the water value, so no other refinement field can coarsen it by accident.</p>
<p><strong>Sizes grade, they never jump.</strong> Steel is ramped from the water size at the
inner wall up to the steel size over <span class="n">1.5</span> mm; the array refinement ramps
back over <span class="n">0.60</span> mm; the notch field blends out between
<span class="n">0.30</span> and <span class="n">3.0</span> mm. There are two reasons, and both
were paid for. A discontinuous size step at the interface produced sliver cells &mdash;
measured minimum shape quality <span class="n">0.46</span>, with every worst cell sitting on the
interface. And an abrupt change in element size scatters a wave much as a change in material
does, so a size step is a spurious reflector.</p>

<h3>Two places where refining would be actively wrong</h3>
<p><strong>The notch is deliberately not the finest region.</strong> Instinct says refine the
scatterer hardest. But an explicit solver has <em>one global</em> time step, set by the smallest
cell over the fastest wave speed, <span class="n">&Delta;t &asymp; C h /(c p<sup>2</sup>)</span>
&mdash; and the notch sits in steel, where <span class="n">c</span> is highest. Refining the tip
to <span class="n">0.09</span> mm drove the step to <span class="n">0.34</span> ns and the run to
<span class="n">178,000</span> steps, against roughly <span class="n">18,000</span> for ordinary
steel cells. A tenfold runtime penalty, for nothing: <strong>the notch faces are exact geometry
at any cell size.</strong> Conformity comes from the boundary representation, not from
refinement. That is the single most useful thing to understand about why this method suits the
problem.</p>
<p><strong>The array face is the finest region, and it is nearly free.</strong> At the water
size a single mesh facet spans a whole <span class="n">0.30</span> mm transducer element, and
<span class="n">28</span> of <span class="n">256</span> elements ended up with no facet of their
own, so their source could not be defined at all. Refining to <span class="n">0.09</span> mm
gives about <span class="n">3.3</span> facets per element. It costs cells but not time steps,
because water is <span class="n">3.8&times;</span> slower than steel, so even these small cells
imply a larger stable step than the steel already forces.</p>

<h3>Where this sizing is tightest &mdash; and it is not the water</h3>
<p>Because water and the array band are the finest regions, the binding constraint is
<strong>steel shear at the pulse's upper edge</strong>. At <span class="n">8</span> MHz the
shear wavelength is <span class="n">0.388</span> mm against a <span class="n">0.448</span> mm
cell, which is about <span class="n">3.5</span> nodes per wavelength. At the
<span class="n">4</span> MHz centre everything sits at <span class="n">6.9</span> or better.
This is a real limitation of the current mesh rather than a solved problem, and it is the one
place where refining the steel would beat raising the element degree.</p>
</div>

<h2 class="col"><span class="num">05</span>The one decision that makes the comparison fair</h2>
<div class="col">
<p>A simulation is not an image. Turning channel data into a picture takes a beamformer, and
beamformers embed dozens of choices &mdash; travel-time models, filters, apodisation, angle
gating. If we wrote our own, any difference between the two images could be blamed on it.</p>
<p>So we did not. We run <strong>the research team's own beamformer</strong> on both datasets,
loaded in place from a read-only checkout of their repository, with the same options their own
simulation script passes on every call. Every image on this page, theirs and ours, comes out of
that same code. Both solvers also emit an identically shaped
<code>channel_data (22801, 256)</code> array at the same sample rate, so the handover is
literally the same array shape from both sides.</p>
<p>That is what makes the rest of this document mean anything: <strong>the forward solver is
the only difference</strong>. The plumbing was verified by feeding their beamformer their own
data and reproducing their archived image &mdash; identical grid, peak in the identical pixel,
amplitude within <span class="n">2.4%</span>.</p>
<p>One declared substitution: their receive-side travel-time routine refuses to run without
CUDA, so we use the CPU routine from the same package. It applies identically to both datasets,
so it cancels out of the comparison rather than favouring either.</p>
</div>

<h2 class="col"><span class="num">06</span>Does our physics work? Exact-solution tests</h2>
<div class="col">
<p>Before comparing anything to k-Wave, the solver was checked against problems with known
closed-form answers. This is what makes the result a measurement rather than an opinion &mdash;
and notably, the reference work contains no convergence, stability or dispersion study to
compare against.</p>
</div>
<div class="tw">
<table>
<caption>Validation against exact solutions &mdash; no fitted parameters anywhere</caption>
<thead><tr><th>Test</th><th>What it proves</th><th class="num">Error</th></tr></thead>
<tbody>
<tr><td>Wave speeds in steel</td><td>the constitutive law, both wave types</td>
    <td class="num">0.002% / 0.000%</td></tr>
<tr><td>Water/steel reflection, normal incidence</td><td>fluid&ndash;solid coupling</td>
    <td class="num">0.00%</td></tr>
<tr><td>Mode conversion at 20&deg;</td><td>the physics the whole method depends on</td>
    <td class="num">0.81%</td></tr>
<tr><td>Refracted shear angle at 20&deg;</td><td>Snell verified, not assumed</td>
    <td class="num">0.55&deg;</td></tr>
<tr><td>Scattering from a cavity</td><td>a defect scatters right, not just flat walls</td>
    <td class="num">~1%</td></tr>
<tr><td>Numerical dispersion, degree 4</td><td>arrival times, the quantity that matters</td>
    <td class="num">0.001%</td></tr>
</tbody>
</table>
</div>
<figure>
  <img src="{img['zoep']}" alt="Mode conversion versus the exact fluid-solid solution">
  <figcaption><b>Mode conversion against the exact fluid&ndash;solid system,
  0&ndash;60&deg;.</b> At the production angle the converted shear amplitude is within
  <span class="n">0.81%</span>. The apparent outliers near <span class="n">15&deg;</span> and
  <span class="n">30&deg;</span> are <em>not</em> solver error &mdash; they sit on the
  compression-critical and leaky-Rayleigh angles, where a plane-wave coefficient is the wrong
  yardstick for a finite beam. At <span class="n">30&deg;</span> the measured
  <span class="n">|R|</span> is <span class="n">0.763</span> against a beam-averaged exact
  <span class="n">0.688</span> and a plane-wave <span class="n">1.000</span>: the simulation is
  closer to the correct finite-beam answer than the textbook curve.</figcaption>
</figure>
<div class="figrow">
  <figure>
    <img src="{img['zoep_ang']}" alt="Refracted angles versus Snell">
    <figcaption><b>Refraction angles.</b> The shear angle is measured from an independent
    slowness fit, so Snell's law is <em>verified</em> rather than assumed &mdash;
    <span class="n">45.53&deg;</span> measured against <span class="n">44.98&deg;</span>
    predicted, and a recovered <span class="n">c<sub>S</sub></span> of
    <span class="n">3117</span> against <span class="n">3100</span> m/s.</figcaption>
  </figure>
  <figure>
    <img src="{img['zoep_err']}" alt="Error versus incidence angle">
    <figcaption><b>Error against angle.</b> The one real limitation is visible here: past the
    shear-critical angle the reflection <em>phase</em> is generated inside an evanescent layer
    only <span class="n">0.17</span> mm thick at <span class="n">60&deg;</span> &mdash; thinner
    than one element &mdash; so its error reaches <span class="n">21.6&deg;</span> and converges
    only at first order. Amplitudes are unaffected. The rule: past a critical angle, size the
    mesh against the decay length, not the wavelength.</figcaption>
  </figure>
</div>
<div class="figrow">
  <figure>
    <img src="{img['pao']}" alt="Cavity scattering versus the exact Pao and Mow series">
    <figcaption><b>Scattering from a defect</b>, against the exact Pao &amp; Mow series.
    Complex gain is unity to <span class="n">0.5%</span> in amplitude and
    <span class="n">0.2&deg;</span> in phase, with zero adjustable parameters. This is the check
    that breaks if the constitutive law or the mode conversion is wrong.</figcaption>
  </figure>
  <figure>
    <img src="{img['pao_dir']}" alt="Scattering directivity versus exact">
    <figcaption><b>Directivity.</b> Not just the forward amplitude but the full angular
    pattern of the scattered field, which is the harder test &mdash; it is sensitive to the
    boundary condition on the cavity, the same condition our notch relies on.</figcaption>
  </figure>
</div>
<figure>
  <img src="{img['pao_wf']}" alt="Scattered wavefield at ka = 3">
  <figcaption><b>The scattering problem itself, at <span class="n">ka = 3</span>.</b> Shown
  because it makes the test legible: a plane shear wave meets a cylindrical void and the
  scattered field is compared, mode by mode, against a series solution with no free parameters.
  Our production notch is exactly this boundary condition applied to a different
  shape.</figcaption>
</figure>

<h2 class="col"><span class="num">07</span>Head-to-head at +20 degrees</h2>
<div class="col">
<p>Same scenario, same imaging code. Ground truth is known because we chose the notch:
<span class="n">4.0</span> mm deep at <span class="n">x = 38.25</span> mm. Blue marks the more
accurate value.</p>
</div>
<div class="tw">
<table>
<caption>TT-T imaging metrics at +20&deg;</caption>
<thead><tr>
  <th>Metric (true value)</th><th class="num">k-Wave</th><th class="num">Ours</th>
  <th class="num">Margin</th></tr></thead>
<tbody>
<tr><td class="row-label">Crack position error (38.25 mm)</td>
  <td class="num">0.413 mm</td><td class="num fem">0.165 mm</td><td class="num">2.5&times;</td></tr>
<tr><td class="row-label">Imaged notch extent (4.0 mm)</td>
  <td class="num">3.48 (&minus;13%)</td><td class="num fem">3.73 (&minus;6.8%)</td>
  <td class="num">half the error</td></tr>
<tr><td class="row-label">Crack / clutter, RMS</td>
  <td class="num">24.0 dB</td><td class="num fem">26.5 dB</td><td class="num">+2.5 dB</td></tr>
<tr><td class="row-label">Crack / clutter, 95th percentile</td>
  <td class="num">17.9 dB</td><td class="num fem">18.9 dB</td><td class="num">+1.0 dB</td></tr>
<tr><td class="row-label">Crack / worst clutter</td>
  <td class="num">11.6 dB</td><td class="num fem">14.1 dB</td><td class="num">+2.5 dB</td></tr>
</tbody>
</table>
</div>
<div class="col">
<p>A single brightness threshold can flatter anybody, so every claim was re-measured across
every reasonable analysis choice &mdash; six extent thresholds, four analysis-region widths,
five clutter guard distances. At this angle we are better in <strong>14 of 15</strong>; the
exception is a tie at the loosest threshold, where both models read
<span class="n">3.85</span> mm.</p>
</div>
<figure>
  <img src="{img['p20']}" alt="k-Wave, FEM, and a defect-free FEM wall at +20 degrees">
  <figcaption><b>+20&deg;, three panels:</b> k-Wave, ours, and ours with the crack removed
  entirely. Each panel is scaled to its own maximum, because the two solvers drive different
  source amplitudes &mdash; only ratios <em>within</em> an image are comparable. Both real
  images carry wall clutter of similar character; that similarity is reassuring for validity
  and is not a win for either side.</figcaption>
</figure>
<figure>
  <img src="{img['p20_clean']}" alt="The same +20 degree images with no annotation at all">
  <figcaption><b>The same data, nothing drawn on it.</b> No wall arcs, no true-notch marker.
  The annotated version tells you where to look, which is exactly what you must not be told
  when judging whether a defect is detectable unaided. Judge the crack from this one; use the
  overlay only to check position.</figcaption>
</figure>

<h2 class="col"><span class="num">08</span>Head-to-head at &minus;20 degrees, and why it matters most</h2>
<div class="col">
<p>One angle is a demonstration; two is a test. Mirroring the steering is the cheapest
independent check available, because the notch is on-axis and the geometry is symmetric &mdash;
so anything that changes materially between <span class="n">+20&deg;</span> and
<span class="n">&minus;20&deg;</span> is telling you about the model rather than the
specimen.</p>
<p>It also carried a <strong>pre-registered prediction</strong>. Before this solve finished we
wrote down what it had to produce for the bandwidth mechanism (section 12) to be real rather
than a story fitted to one result: contrast <span class="n">23&ndash;25</span> dB and extent
<span class="n">3.7&ndash;4.2</span> mm, and we stated that a materially worse result would
mean reporting the win as one angle only. It came back at <strong><span class="n">24.0</span> dB
and <span class="n">3.85</span> mm</strong>, both inside the range. That is the difference
between an explanation and a rationalisation.</p>
</div>
<div class="tw">
<table>
<caption>TT-T imaging metrics at &minus;20&deg;</caption>
<thead><tr>
  <th>Metric (true value)</th><th class="num">k-Wave</th><th class="num">Ours</th>
  <th class="num">Margin</th></tr></thead>
<tbody>
<tr><td class="row-label">Crack position error (38.25 mm)</td>
  <td class="num">0.332 mm</td><td class="num fem">0.084 mm</td><td class="num">4.0&times;</td></tr>
<tr><td class="row-label">Imaged notch extent (4.0 mm)</td>
  <td class="num kw">3.85 (&minus;3.8%)</td><td class="num tie">3.85 (&minus;3.8%)</td>
  <td class="num tie">exact tie</td></tr>
<tr><td class="row-label">Crack / clutter, RMS</td>
  <td class="num">24.5 dB</td><td class="num fem">26.3 dB</td><td class="num">+1.8 dB</td></tr>
<tr><td class="row-label">Crack / clutter, 95th percentile</td>
  <td class="num">18.4 dB</td><td class="num fem">18.9 dB</td><td class="num">+0.5 dB</td></tr>
<tr><td class="row-label">Crack / worst clutter</td>
  <td class="num">11.8 dB</td><td class="num fem">13.5 dB</td><td class="num">+1.7 dB</td></tr>
</tbody>
</table>
</div>
<div class="col">
<p><strong>What replicated and what did not.</strong> Contrast and position replicated
cleanly: better at every guard distance and every analysis-region width, at both angles.
<strong>Sizing did not.</strong> At this angle both models read
<span class="n">3.85</span> mm &mdash; a genuine tie, and we do not present it as anything else.
Across the sweep we take <span class="n">11</span> of <span class="n">15</span> here against
<span class="n">14</span> of <span class="n">15</span> at <span class="n">+20&deg;</span>, and
all four losses are notch extent: ties at thresholds <span class="n">0.20</span> and
<span class="n">0.25</span>, with k-Wave nearer truth at <span class="n">0.30</span> and
<span class="n">0.40</span>.</p>
<p>That asymmetry is the most interesting number on this page. Our own sizing barely moved
between angles (<span class="n">3.73</span> to <span class="n">3.85</span> mm); theirs improved
substantially. The honest reading is that <strong>our sizing advantage is specific to
<span class="n">+20&deg;</span></strong> on the evidence available, and that a third angle is
needed before it can be called general.</p>
</div>
<figure>
  <img src="{img['m20']}" alt="k-Wave versus FEM at minus 20 degrees">
  <figcaption><b>&minus;20&deg;, annotated.</b> Note that the clutter structure mirrors with
  the steering direction &mdash; the bright band that sits to the right of the crack at
  <span class="n">+20&deg;</span> appears on the left here. That mirroring is itself evidence:
  it identifies the feature as beam-related rather than a property of the wall or the
  mesh.</figcaption>
</figure>
<figure>
  <img src="{img['m20_clean']}" alt="The same minus 20 degree images with no annotation">
  <figcaption><b>&minus;20&deg;, unannotated.</b> Same pairing as above: judge detectability
  from this, position from the overlay.</figcaption>
</figure>

<div class="verdict col">
  <span class="kicker">Angle consistency</span>
  <p>Our sizing moves less with steering angle than theirs:
  <span class="n">3.73</span> and <span class="n">3.85</span> mm against their
  <span class="n">3.48</span> and <span class="n">3.85</span> mm &mdash; a
  <strong><span class="n">3%</span> spread against <span class="n">11%</span></strong>. Both
  datasets pass through the same imaging chain, so an imaging quirk would move both equally.</p>
  <p>For an inspection tool this matters more than any single decibel figure. A real crack is
  never conveniently on-axis, and a sizing error that swings with beam angle is one you cannot
  calibrate away. But <span class="n">n = 2</span> cannot separate a real trend from a
  coincidence, and this is the claim most in need of a third angle.</p>
</div>

<h2 class="col"><span class="num">09</span>Artifacts: what they are and what we removed</h2>
<div class="col">
<p>The engineer who wrote the k-Wave simulation reviewed our images and said they had
<em>"some artifacts"</em>. It is the first thing any reviewer says, so it is worth answering
precisely rather than defending.</p>
<p>An <strong>artifact</strong> is brightness where nothing real exists. The beamformer assumes
every echo took one specific path; energy arriving by another route, or invented numerically,
still lands at whatever depth its arrival time implies. The standard is unforgiving:
<strong>a defect-free steel wall must image black.</strong> Neither model's does.</p>
<p><strong>Ours is nonetheless the cleaner of the two</strong> &mdash; crack against clutter
RMS <span class="fem n">26.5</span> dB against <span class="kw n">24.0</span>, and against the
single worst clutter pixel <span class="fem n">14.1</span> against
<span class="kw n">11.6</span>, unanimous over all five guard distances at both angles.</p>
<p><strong>Ours looks dirtier, and that part is presentation.</strong> These panels use a
<span class="n">&minus;40</span> dB <em>log</em> scale; their published images are linear
min-max. Our clutter 95th percentile sits about <span class="n">15</span> dB below the crack
peak, which is <span class="n">17%</span> of it &mdash; a barely visible grey on a linear scale,
and the bright middle of the colour map on log. Same data. Their scale suppresses precisely what
ours puts on display.</p>

<h3>The reduction programme</h3>
<p>Two independent changes were tested, and both work. They act in different places, so their
gains add rather than overlap.</p>
</div>
<div class="tw">
<table>
<caption><b>Cumulative artifact reduction.</b> Lower is cleaner in the right three columns.
Whole-wall figures come from the figure below; the edge band is the worst region, measured
separately.</caption>
<thead><tr><th>Configuration</th><th class="num">Crack vs clutter</th>
  <th class="num">Whole wall, +20&deg;</th><th class="num">Whole wall, &minus;20&deg;</th>
  <th class="num">Edge band, +20&deg;</th></tr></thead>
<tbody>
<tr><td class="row-label">Starting point</td><td class="num">24.0 dB</td>
  <td class="num">&minus;22.8 dB</td><td class="num">&minus;22.7 dB</td>
  <td class="num">&minus;21.4 dB</td></tr>
<tr><td class="row-label">+ imaging-operator anti-aliasing</td><td class="num fem">26.5 dB</td>
  <td class="num fem">&minus;25.4 dB</td><td class="num fem">&minus;25.3 dB</td>
  <td class="num">&minus;23.0 dB</td></tr>
<tr><td class="row-label">+ shear-matched boundary and sponge</td><td class="num">26.5 dB</td>
  <td class="num">&minus;25.4 dB</td><td class="num">&minus;25.2 dB</td>
  <td class="num fem">&minus;23.9 dB</td></tr>
<tr><td class="row-label"><b>Total change</b></td><td class="num fem"><b>+2.5 dB</b></td>
  <td class="num fem"><b>&minus;2.6 dB</b></td><td class="num fem"><b>&minus;2.5 dB</b></td>
  <td class="num fem"><b>&minus;2.5 dB</b></td></tr>
</tbody>
</table>
</div>
<figure>
  <img src="{img['artred']}" alt="Wall images before and after treatment, plus a clutter profile, +20 degrees">
  <figcaption><b>+20&deg;: the reduction, measured and shown.</b> Top and middle are the wall
  before any treatment and after both, on <em>one shared colour scale</em>, each referenced to
  its own crack peak &mdash; the ripple across the mid-wall thins noticeably while the crack
  itself is untouched. Bottom: clutter level along the wall with the crack column excluded. The
  untreated curve sits <span class="n">2&ndash;3</span> dB above the others almost everywhere.
  The two treated curves overlap because the boundary fix acts at the edges, not across the
  wall.</figcaption>
</figure>
<figure>
  <img src="{img['artred_m20']}" alt="The same three-panel artifact figure at minus 20 degrees">
  <figcaption><b>&minus;20&deg;: it replicates.</b> Whole-wall clutter falls
  <span class="n">2.59</span> dB here against <span class="n">2.62</span> dB at
  <span class="n">+20&deg;</span> &mdash; agreement to <span class="n">0.03</span> dB across a
  mirrored beam. A treatment that only worked at one steering angle would be a tuning
  coincidence; this one is a property of the method.</figcaption>
</figure>
<div class="col">
<h3>What each change does, and why only one is in production</h3>
<p><strong>Imaging-operator anti-aliasing</strong> suppresses aliasing inside the migration
operator, which is the textbook cause of streak clutter at steep image angles. It is applied to
<em>both</em> datasets, so it improved k-Wave too &mdash; from <span class="n">22.8</span> to
<span class="n">24.0</span> dB &mdash; but it improved ours more, roughly doubling our margin.
Crack sizing and position did not move at all: clutter removed without touching the
measurement. <b>This is in the production configuration.</b></p>
<p><strong>The absorbing boundary</strong> was damping compression and shear at the same rate,
over-damping the shear wave by about <span class="n">30%</span> of its amplitude. Correcting it
to the true shear impedance, and adding a graded sponge layer across the unused margins, takes a
further <span class="n">0.8</span> dB off the clutter <em>at the wall edges</em>, where the
artefact is worst, while leaving the wall as a whole unchanged. It replicates at the second
angle (<span class="n">0.7</span> dB), and the defect-free wall confirms it independently: that
wall, where every visible feature is numerical, comes out <span class="n">0.95</span> dB
cleaner.</p>
<p><strong>It is nonetheless not in production</strong>, because it shifts the measured crack
extent by about <span class="n">0.12</span> mm in the same direction at both angles. At
<span class="n">+20&deg;</span> that is <em>toward</em> truth
(<span class="n">3.73&rarr;3.85</span> mm); at <span class="n">&minus;20&deg;</span> it is
<em>away</em> (<span class="n">3.85&rarr;3.73</span>). A cleaner image bought with a bias in the
quantity we are selling is not a trade to make silently, so the published results use the
original boundary and this sits on the table as a characterised option.</p>
</div>
<figure>
  <img src="{img['bnd_clean']}" alt="Four boundary treatments at +20 degrees, unannotated">
  <figcaption><b>The boundary variants side by side, unannotated.</b> k-Wave, then our original
  boundary, the shear-matched correction, and the correction plus sponge. Included for
  completeness and as a caution: at <span class="n">0.8</span> dB the difference between these
  panels is <em>below the visual threshold</em> of a heat map whose panels are each normalised to
  their own maximum. This is why the quantitative figure above exists, and why a reviewer should
  not be asked to judge a sub-decibel change by eye.</figcaption>
</figure>
<figure>
  <img src="{img['healthy_clean']}" alt="Defect-free wall under the corrected boundary treatment">
  <figcaption><b>A defect-free wall, unannotated.</b> There is no defect anywhere in this
  simulation, so <em>every</em> feature visible is numerical &mdash; which makes this the
  cleanest possible measurement of an artifact floor. It is the run that ruled the domain
  boundary out as the dominant artifact source.</figcaption>
</figure>
<div class="col">
<h3>Testing the side boundaries directly: widen the domain until they cannot matter</h3>
<p>Every absorbing boundary is an approximation, so the cleanest test of whether ours is the
artefact source is to move it out of reach and stop approximating. We widened the model laterally
from <span class="n">93</span> to <span class="n">165</span> mm, taking the margin outboard of the
aperture from <span class="n">8</span> mm to <span class="n">45</span> mm. That is a timing
argument, not a comfort margin: it delays the first side-wall return from about
<span class="n">29.5</span> to <span class="n">42.5</span> microseconds, moving it clear of the
crack echo at <span class="n">33&ndash;40</span> microseconds. The prediction and the falsifier
were written down before the run &mdash; a real reduction meant the edge excess dropping more than
<span class="n">1.5</span> dB, a null meant less than <span class="n">0.5</span> dB.</p>
<p><strong>The result is a null.</strong> On the pinned edge metric the excess moved
<span class="n">+0.24</span> dB &mdash; marginally <em>louder</em>, inside the null band. Sizing
did not move (<span class="n">3.73</span> mm at both widths), nor did position. Overall clutter
contrast improved slightly (<span class="n">26.5</span> to <span class="n">26.9</span> dB), and we
are not claiming that as a domain effect: re-meshing at a larger extent changed the smallest edge
in the mesh, which lowered the global time step from <span class="n">0.3666</span> to
<span class="n">0.3288</span> ns, and a smaller time step is less numerically dispersive on its
own. The change carried a passenger, so the small win is unattributed.</p>
<p>The null is the useful part. The side boundaries are not the source of the residual edge
artefact, which leaves the array's own grating lobe as the leading explanation &mdash; and that one
is derivable rather than arguable.</p>
</div>
<figure>
  <img src="{img['wide_clean']}" alt="k-Wave, the standard domain and the widened domain at +20 degrees, unannotated">
  <figcaption><b>Widening the domain by 1.8x does not remove the edge artefact.</b> k-Wave, then
  our standard domain, then the same model with the side boundaries moved from 8 mm to 45 mm
  outboard of the aperture &mdash; far enough that their reflections arrive after the crack echo
  rather than during it. The bright feature near the right-hand edge is essentially
  unchanged.</figcaption>
</figure>
<div class="col">
<h3>What is left, and the part that is not ours</h3>
<p>A residual edge artefact survives, and six candidate causes have now been tested and
eliminated: the absorbing boundary, the domain width, mesh coarsening, sample-rate aliasing in the
imaging chain, the mass matrix, and migration-operator aliasing &mdash; the last of which removed most of the
excess at <span class="n">+20&deg;</span> (<span class="n">+1.76</span> to
<span class="n">+0.50</span> dB) but much less at <span class="n">&minus;20&deg;</span>
(<span class="n">+4.05</span> to <span class="n">+3.47</span> dB), so it contributes without
explaining.</p>
<p>Part of it is not ours to fix, and this can be derived rather than argued. The research
team's own script computes the no-grating-lobe condition
<span class="n">pitch &le; &lambda;/(1+|sin&nbsp;&theta;|)</span>. For this scenario the limit
is <span class="n">0.279</span> mm and the array pitch is <span class="n">0.30</span> mm, with a
grating-lobe-free ceiling of <span class="n">3.73</span> MHz against a
<span class="n">4</span> MHz centre. <strong>A full-amplitude alias of the main beam therefore
exists by array geometry alone, in both simulations.</strong> Their own comment notes it cannot
be removed by apodisation, because at the alias angle every element is back in phase by
definition. The only levers are lower steering angle, lower frequency or finer element pitch,
and all three are hardware decisions.</p>
</div>

<h2 class="col"><span class="num">10</span>Proving the bright spot is the crack</h2>
<div class="col">
<p>A bright patch in the right place is not proof. So we simulated the identical wall with
<strong>no crack at all</strong>, and imaged it the same way.</p>
<p>In that defect-free run the notch location peaks <span class="n">6.1</span> dB
<em>below</em> the worst clutter elsewhere in the wall &mdash; there is no feature there at
all. The cracked run's response at the same place is <span class="n">18.4</span> dB above it.
Subtracting the two channel-data records cancels the wall coherently and leaves a compact
feature at extent <span class="n">3.85</span> mm with contrast
<span class="n">27.8</span> dB.</p>
<p>The honest limit: removing the notch also removes the mesh cells around it, which changes
the stable time step, so the two runs reach the common sample grid from different step sizes.
The residual floor is <span class="n">2.3%</span> of the difference peak, leaving about
<span class="n">13</span> dB of headroom. Real cancellation, not an exact null &mdash; and the
cleanest version of this test would be a defect-free k-Wave run at the same settings, which is
a script parameter change for the research team and the one thing we would ask of them.</p>
</div>
<figure>
  <img src="{img['base']}" alt="Cracked, healthy, and difference images">
  <figcaption><b>Crack minus healthy.</b> The wall is common to both runs and cancels; what
  survives is the defect. Shared colour scale across all three panels.</figcaption>
</figure>

<h2 class="col"><span class="num">11</span>The mechanism behind our own convergence</h2>
<div class="col">
<h3>Resolution must be sized for bandwidth, not centre frequency</h3>
<p>A mesh built for "four nodes per wavelength at 4 MHz" sounds adequate and is not. A
single-cycle pulse carries roughly <span class="n">100%</span> bandwidth &mdash; real energy
out to <span class="n">6&ndash;8</span> MHz &mdash; and at those frequencies the same mesh has
barely half the nodes it needs. The mesh then low-passes our own pulse as it travels, and
because <strong>axial resolution is set by bandwidth, not centre frequency</strong>, that one
oversight explains a whole family of symptoms at once: a notch smeared to
<span class="n">8.07</span> mm, a weak crack response, and poor contrast. Raising the element
degree and refining recovers all of them together.</p>
<p>Two competing explanations were eliminated by measurement first. The <strong>source
pulse</strong> was never the limit &mdash; our emitted pulse is broader than k-Wave's returned
echo. And the energy is <strong>genuinely lost, not merely delayed</strong>: a whole-record
measure shows the high band missing, and the loss scales with element order, which is the
signature of high-wavenumber numerical dispersion rather than of a boundary reflection.</p>
</div>
<figure>
  <img src="{img['bw']}" alt="Returned pulse spectra and image metrics versus refinement">
  <figcaption><b>Left:</b> the returned pulse's spectrum, computed from the channel data
  itself. Each refinement recovers more of the <span class="n">4&ndash;6</span> MHz band.
  <b>Right:</b> as that band returns, both image metrics move &mdash; sizing toward the true
  <span class="n">4.0</span> mm, contrast past k-Wave's. This is the evidence behind the
  configuration choice: degree 3 <em>loses</em> to k-Wave at both angles, degree 4 on a finer
  mesh wins at both.</figcaption>
</figure>
<div class="verdict warn col">
  <span class="kicker">An important limit on this explanation</span>
  <p>Bandwidth explains <em>our own</em> convergence. It does <strong>not</strong> explain the
  margin over k-Wave, and it would be wrong to present it that way. Their returned pulse is
  <em>broader</em> than ours &mdash; <span class="n">4.17</span> MHz against our
  <span class="n">3.33</span> &mdash; and they still size the notch worse at
  <span class="n">+20&deg;</span>. On raw bandwidth <strong>they are ahead of us</strong>.</p>
</div>

<h2 class="col"><span class="num">12</span>Two candidate explanations, both eliminated</h2>
<div class="col">
<p>If our geometry is so much more faithful, that should be measurable. We tested it directly,
inside our own solver, changing exactly one thing at a time &mdash; which is possible for us
and not for them, since we can instrument our own code.</p>
<p><strong>Staircase the inner wall</strong> at k-Wave's own <span class="n">50</span>
&micro;m spacing, on a defect-free pipe where every bright pixel is therefore numerical. It
moved the clutter floor by <strong><span class="n">0.61</span> dB</strong> RMS &mdash;
consistent in direction across all three measures, and far too small to explain the margin.
This project had asserted since its design phase that our advantage came from conforming
geometry. That claim is <strong>withdrawn</strong>.</p>
<p><strong>Fill the crack</strong> with the fictitious material k-Wave uses in place of a void
(<span class="n">500</span> m/s compression, zero shear, read from their script). Effect on the
crack response: <strong><span class="n">0.07</span> dB</strong>, with no measurable change in
sizing or position. Predicted in advance to be near-null, because a filled crack still reflects
<span class="n">98.9%</span> of what a true free surface would, so almost no energy enters it to
be got wrong.</p>
</div>
<div class="verdict dead col">
  <span class="kicker">Where that leaves the explanation</span>
  <p><strong>We measure better and cannot yet attribute it.</strong> That is a legitimate
  scientific position and a stronger one than picking a story that collapses under questioning.
  Both figures are recorded in full in the branch README (&sect;4.10, &sect;4.12).</p>
  <p>What remains untested sits inside k-Wave, where we cannot instrument it: its single
  precision, its absorbing layer, and its sub-pixel interface blending. Testing those would
  need their cooperation, not more compute on our side.</p>
</div>

<h2 class="col"><span class="num">13</span>What we cannot claim</h2>
<div class="ledger col">
  <div class="claim"><span class="tag yes">Solid</span><div>
    <p>Better crack-to-clutter contrast than k-Wave, at both angles.</p>
    <p>Unanimous 10/10 across every guard distance at both angles. The strongest claim on the
    page.</p></div></div>
  <div class="claim"><span class="tag yes">Solid</span><div>
    <p>The physics is right to about 1%.</p>
    <p>Six exact-solution checks, no fitted parameters. The reference work has no
    equivalent.</p></div></div>
  <div class="claim"><span class="tag part">Bounded</span><div>
    <p>Contrast advantage of +2.5 dB.</p>
    <p>A <b>lower bound only</b> &mdash; still improving at our last refinement, so the
    converged value is unknown. No Richardson error bars computed.</p></div></div>
  <div class="claim"><span class="tag part">Bounded</span><div>
    <p>More accurate crack sizing.</p>
    <p>True at <span class="n">+20&deg;</span> (&minus;6.8% against &minus;13%) and an
    <b>exact tie</b> at <span class="n">&minus;20&deg;</span>. Not an every-angle claim on this
    evidence.</p></div></div>
  <div class="claim"><span class="tag part">Bounded</span><div>
    <p>Better crack localisation.</p>
    <p>Quote as <b>sub-pixel, &le;0.25 mm</b>, never as a ratio. Our own value moved 0.24 mm
    between meshes &mdash; about one image pixel, comparable to the whole claimed
    advantage.</p></div></div>
  <div class="claim"><span class="tag part">Quantified</span><div>
    <p>How much each of k-Wave's geometry approximations costs.</p>
    <p>Staircasing measured at <b>0.61 dB</b>, the crack fill at <b>0.07 dB</b> &mdash; both too
    small to account for the margin, so neither is offered as its explanation.</p></div></div>
  <div class="claim"><span class="tag dead">Withdrawn</span><div>
    <p>"We win because the mesh conforms to the geometry."</p>
    <p>Measured at &le;1 dB by our own controlled experiment. Not used anywhere. The conforming
    mesh remains a <em>capability</em>, and its payoff should appear on geometry a grid handles
    badly &mdash; which is untested.</p></div></div>
  <div class="claim"><span class="tag no">Open</span><div>
    <p>The residual edge artefact.</p>
    <p>Six causes eliminated, none of them the answer, and it is worse at
    <span class="n">&minus;20&deg;</span> than <span class="n">+20&deg;</span>. Part of it is a
    grating lobe inherent to the array geometry and present in both models.</p></div></div>
  <div class="claim"><span class="tag no">Not done</span><div>
    <p>Generalisation beyond this case.</p>
    <p>Two angles, one crack size, one crack shape, <b>2-D only</b>. No defect-free k-Wave run
    exists at these settings, so that comparison is ours alone.</p></div></div>
</div>

<h2 class="col"><span class="num">14</span>What actually limits the speed</h2>
<div class="col">
<p>Relevant because any 3-D discussion depends on it, and because several of these numbers were
estimated first and measured later &mdash; the measurements are what we would plan against.</p>

<h3>Why the time loop was portable at all</h3>
<p>One explicit step is a single sparse matrix-vector product plus a few elementwise vector
operations. Count arithmetic against bytes and the ratio is lopsided: about two floating-point
operations per matrix entry, but twelve bytes fetched to get that entry. The kernel is
<strong>memory-bandwidth bound</strong> &mdash; it spends its life waiting for memory &mdash; and
that one fact predicts everything else here, including why adding CPU cores barely helps and why
a GPU helps enormously.</p>
<p>It also made the port small. The loop touches neither PETSc nor DOLFINx: the framework
assembles the operators once and the loop is then <code>scipy.sparse</code> alone. So this was a
two-line swap to <code>cupy</code>/cuSPARSE, not a CUDA-enabled finite-element stack. Worth
knowing, because the framework's own GPU route is <em>blocked</em> &mdash; its CUDA assembly
extension cannot be used with the standard container distributions, which ship the linear-algebra
backend without CUDA support. We verified that on our own image rather than taking the
documentation's word for it.</p>

<h3>Validating a different backend</h3>
<p>A GPU result is <strong>not</strong> bit-identical to a CPU one and never will be: the sparse
library sums in a different order, so the two differ at round-off from the first step. The
tempting check &mdash; compare the vectors, see a small number, declare victory &mdash; is the
wrong check. A solver can agree to one part in a million in amplitude and still run
systematically <em>late</em>, and in this measurement late is a depth error.</p>
<p>So the gate scores <strong>arrival time</strong>, by sub-sample cross-correlation rather than a
threshold crossing (a first-break pick jumps a whole sample as soon as noise nudges it, which
would hide exactly the drift being tested for). Thresholds were fixed before the first run. Two
tests passed: a backend A/B at identical settings, and a full-length run scored against the stored
CPU record &mdash; <span class="n">1.7e-12</span> samples of drift against a
<span class="n">0.01</span> sample threshold, mean drift <span class="n">2e-14</span> so no
systematic lead or lag, and every imaging metric identical to the published value at every quoted
digit.</p>
<ul>
<li><strong>The time loop runs about 19&times; faster on one consumer GPU, measured and
validated.</strong> The hot loop touches neither PETSc nor DOLFINx - assembly happens once, then
the loop is <code>scipy.sparse</code> only - so this needed a <code>cupy</code>/cuSPARSE swap of
two lines rather than a CUDA-enabled FEM stack. On the production problem
(<span class="n">1.47</span> M unknowns, <span class="n">105</span> M nonzeros)
<span class="n">2.4</span> hours per angle becomes <span class="n">7.7</span> minutes. It is a
pure bandwidth ratio, which is also why double precision costs little here despite this card
running fp64 arithmetic at a small fraction of fp32.
<br><b>The validation is the part that matters.</b> cuSPARSE reduces in a different order, so the
GPU path is not bit-identical and never will be - and a solver can agree in amplitude while
running systematically late, which would be a depth error. So the gate is a <em>timing</em> gate
with thresholds fixed before the first run. Two tests, both passed: a backend A/B at identical
flags over <span class="n">8,184</span> steps, and a full-length run scored against the stored CPU
production record. Arrival-time shift <span class="n">1.7e-12</span> samples against a
<span class="n">0.01</span> sample threshold, mean shift <span class="n">2e-14</span> so no
systematic lead or lag, and every imaging metric identical to the published value at every quoted
digit.</li>
<li><strong>Parallelism gives 1.71&times;, not the 4&ndash;8&times; a core count suggests.</strong>
DOLFINx is MPI-parallel and partitions almost perfectly (imbalance
<span class="n">&le;1.02&times;</span>), but the operation is <em>memory-bandwidth</em> bound:
each step streams about <span class="n">1.26</span> GB through a sparse product at roughly
<span class="n">24</span> GB/s, near this machine's limit. Cores share one memory bus, so
returns are sublinear by construction. <b>Do not promise a core-count speed-up.</b></li>
<li><strong>A matrix-free prototype came out 10&times; slower</strong> than the code we already
run. The algorithm is right and is standard for high-order elements, but pure NumPy allocates
about <span class="n">120</span> MB of temporaries per application. Realising it needs a
compiled kernel &mdash; a much larger commitment than it first appears.</li>
<li><strong>The real headroom is the time step.</strong> Ours comes from a conservative rule of
thumb. Computing the exact stability limit directly &mdash;
<code>2/sqrt(lambda_max(M<sup>-1</sup>K))</code> by power iteration &mdash; shows our step sits
at <span class="n">16.4%</span> of it, i.e. roughly <span class="n">6&times;</span> available. An
independent code's published rule agrees with that measurement to
<span class="n">5%</span>. A first trial at <span class="n">4&times;</span> ran stably with peak
amplitude unchanged to <span class="n">0.01%</span>; it needs one validation pass against known
arrival times before adoption, since a larger step also raises temporal dispersion, and timing
accuracy is the entire point of this simulation.</li>
</ul>
<p>For scale: the production configuration is <span class="n">1.47</span> million unknowns,
<span class="n">163,680</span> steps at <span class="n">0.366</span> ns &mdash; about
<span class="n">2.4</span> hours per steering angle on one CPU core, or
<span class="n">7.7</span> minutes on a consumer GPU, with no licence either way.</p>
<p><strong>What that changes, and what it does not.</strong> Work deferred purely on cost &mdash;
more steering angles, a crack-size sweep, convergence error bars &mdash; moves from days to
minutes, and those are exactly the experiments that would firm up the claims this document marks as
bounded. The widened-domain test in section 9 is the first of them: it needed a
<span class="n">1.5&times;</span> larger model over <span class="n">182,000</span> steps and cost
<span class="n">12</span> minutes, where on the CPU it would have been most of a working day. It changes no result:
the GPU reproduces the CPU numbers, checked rather than assumed.</p>
<p>It also does <strong>not</strong> unlock 3-D, and it is worth being precise about why. 3-D is
limited by <em>memory</em>, not speed: storing this operator at this element order in three
dimensions needs far more than a consumer card holds. The route runs through a matrix-free
solver, which stores no operator at all and recomputes element contributions instead &mdash;
trading bandwidth for arithmetic, which is a bad trade on a CPU and a good one on a GPU. So
matrix-free and 3-D are one project, not two, and the GPU is its precondition rather than its
substitute.</p>
</div>

<h2 class="col"><span class="num">15</span>Slide map</h2>
<div class="col"><p>Suggested deck order. Figures live under
<code>src/fenics/results/</code>.</p></div>
<div class="slides">
  <div class="slide"><div><b>The inspection problem</b>
    <span>Pipe, wall, a 42%-through-wall crack on the far side. The answer is a time, not a
    brightness. <em>schematic or text</em></span></div></div>
  <div class="slide"><div><b>Why the beam is steered</b>
    <span>Mode conversion, the 15.3&deg; critical angle, pure shear at ~45&deg;, the TT-T path.
    <em>viz/wavefield_snap_p20deg_t31p0us.png</em></span></div></div>
  <div class="slide"><div><b>The wavefield &mdash; play this</b>
    <span>Compression in water, shear in steel, half-skip to the notch.
    <em>viz/wavefield_web.gif</em></span></div></div>
  <div class="slide"><div><b>Grid versus mesh</b>
    <span>Staircase against exact arc; the crack as a void, not fake material.
    <em>viz/mesh_zoom.png</em></span></div></div>
  <div class="slide"><div><b>How the mesh is sized</b>
    <span>h from the wavelength per region; the slowest material is finest; why refining the
    crack would be wrong. <em>the four-row sizing table</em></span></div></div>
  <div class="slide"><div><b>Making it a fair fight</b>
    <span>Their beamformer on our data with their own options, so the forward solver is the
    only difference. <em>no figure</em></span></div></div>
  <div class="slide"><div><b>Validation against exact solutions</b>
    <span>0.81% mode conversion, 0.55&deg; shear angle, ~1% defect scattering, no fitted
    parameters. <em>zoeppritz/amplitude.png + cavity_scattering/dscf_vs_exact.png</em></span></div></div>
  <div class="slide"><div><b>Head-to-head, +20&deg;</b>
    <span>The metric table; 14/15 robustness checks.
    <em>table + compare/compare_p20deg_nooverlay.png</em></span></div></div>
  <div class="slide"><div><b>The second angle</b>
    <span>Pre-registered prediction, landed inside the range. Contrast replicates; sizing ties.
    <em>table + compare/compare_m20deg_nooverlay.png</em></span></div></div>
  <div class="slide"><div><b>Artifact reduction</b>
    <span>2.6 dB off the whole wall, replicating to 0.03 dB across mirrored beams.
    <em>viz/artifact_reduction_p20deg.png</em></span></div></div>
  <div class="slide"><div><b>The crack is real</b>
    <span>A defect-free wall images empty; the difference isolates the crack.
    <em>compare/baseline_subtract_20deg.png</em></span></div></div>
  <div class="slide"><div><b>Why: bandwidth, with the caveat</b>
    <span>Resolution must follow bandwidth &mdash; and k-Wave is ahead of us on it.
    <em>viz/bandwidth_convergence.png</em></span></div></div>
  <div class="slide"><div><b>Both candidate explanations eliminated</b>
    <span>Staircase 0.61 dB, crack fill 0.07 dB; the geometry claim withdrawn.
    <em>no figure &mdash; quote the two numbers</em></span></div></div>
  <div class="slide"><div><b>What we cannot claim</b>
    <span>The ledger: lower bounds, the sizing tie, the open artefact, the withdrawn claim.
    <em>table</em></span></div></div>
</div>

<footer>
  <p>Every figure regenerates from committed code and cached data; nothing is hand-drawn. Full
  record including all traps and withdrawn claims:
  <code>F:/code/readme/rnd-nima-FEA-README.md</code>. Reproduction recipe:
  <code>src/fenics/README.md</code>.</p>
</footer>
"""
