r"""Body copy for the technical dossier page. Built by viz/build_artifacts.py.

Kept in its own module because the page is long and the builder should stay readable.
Nothing here computes anything - every number is a measured result recorded in the branch
README, and every figure is generated by another script in this folder.
"""
from __future__ import annotations


def body(img: dict, c5) -> str:
    """img maps short keys to data URIs; c5 is None while that experiment is running."""
    c5_block = ("""
    <div class="verdict warn">
      <span class="kicker">Running as this was written</span>
      <p>The last experiment, <strong>C5</strong>, is still solving. It tests the one surviving
      explanation for our advantage, and its prediction is already on record above. This page
      gets updated with the outcome either way &mdash; including if the prediction is
      wrong.</p>
    </div>""" if c5 is None else f"""
    <div class="verdict">
      <span class="kicker">C5 result</span>
      <p>{c5}</p>
    </div>""")

    return f"""
<header class="mast">
  <p class="eyebrow">DarkVision R&amp;D &middot; branch rnd-nima-fea &middot; 13 August 2026</p>
  <h1>Simulating a crack in a pipe wall, twice, and finding out which answer to trust</h1>
  <p class="lede col">An open-source finite-element ultrasound simulation, benchmarked
  head-to-head against the research team's MATLAB k-Wave model, on their scenario, through
  their own imaging code. This is the long version: the physics, the method, every number,
  and every claim we could not support.</p>
</header>

<div class="verdict good col">
  <span class="kicker">The short version</span>
  <p>At both usable steering angles our simulation locates and <strong>sizes the crack more
  accurately than k-Wave</strong> &mdash; sizing error <span class="n">&minus;6.8%</span> and
  <span class="n">&minus;3.8%</span> against their <span class="n">&minus;19%</span> and
  <span class="n">+58%</span> &mdash; and is closer to truth in <span class="n">29</span> of
  <span class="n">30</span> robustness checks. The underlying physics is validated against
  exact analytical solutions to about <span class="n">1%</span>.</p>
  <p>Two bounds worth stating up front. The contrast advantage is a <em>floor</em>, not a
  converged number. And of k-Wave's two geometry approximations we have now measured what each
  costs &mdash; <span class="n">0.61</span> dB and <span class="n">0.07</span> dB &mdash; so
  neither is offered as the explanation for the margin; a third candidate is under test with its
  prediction on record.</p>
</div>

<h2 class="col"><span class="num">01</span>What the inspection actually has to do</h2>
<div class="col">
<p>An in-line inspection tool travels inside a pipeline and has to find cracks in the wall
from the inside, swimming in fluid, without touching anything. The specific target here is a
steel pipe with a <span class="n">9.525</span> mm wall &mdash; <span class="n">387.35</span> mm
inner diameter, <span class="n">406.40</span> mm outer &mdash; carrying a notch cut into its
<em>outer</em> surface, <span class="n">4.0</span> mm deep and <span class="n">1.0</span> mm
wide. That is <span class="n">42%</span> through-wall, on the far side of the wall, viewed
from <span class="n">20</span> mm away through water.</p>
<p>The instrument is a <strong>256-element phased array</strong> on a
<span class="n">0.30</span> mm pitch firing a <strong>single cycle</strong> of
<span class="n">4</span> MHz. The single cycle matters: a short pulse is what makes echoes
separable in time, and time is what this measurement is made of.</p>
<h3>The answer is a time, not a brightness</h3>
<p>The tool does not photograph the crack. It measures <em>when</em> echoes return and infers
geometry from arrival times. Get an amplitude 20% wrong and the picture is dimmer. Get a time
wrong by a fraction of a microsecond and the crack appears where it is not, or its depth is
misread. Every numerical choice in this project follows from that asymmetry:
<strong>timing matters far more than amplitude</strong>.</p>
</div>

<h2 class="col"><span class="num">02</span>Why the beam is steered, and what "TT-T" means</h2>
<div class="col">
<p>Fired straight at the wall, a narrow notch is nearly invisible &mdash; it presents almost
no surface back towards the array, and its echo is buried under the much louder front-wall
reflection. So the array steers to <span class="n">20&deg;</span>, and something useful happens
at the water/steel interface.</p>
<p>Steel carries two wave types: <strong>compression</strong> (particles move along the
direction of travel, <span class="n">5700</span> m/s) and <strong>shear</strong> (across it,
<span class="n">3100</span> m/s). Water carries only compression. At an angle, an incoming
compression wave converts into <em>both</em> inside the steel, in proportions set by the angle.
That is <em>mode conversion</em>.</p>
<p>At <span class="n">20&deg;</span> it is exploited deliberately. Snell's law puts the
critical angle for compression at <span class="n">15.3&deg;</span>, so beyond that it cannot
propagate into the steel at all &mdash; it becomes evanescent and dies at the surface. What
survives is an almost <strong>pure shear wave at about 45&deg;</strong>, which travels down
through the wall, reflects off the outer surface, and illuminates the notch from the side.
That is the geometry a surface-breaking crack presents best.</p>
<p><code>TT-T</code> names that path: transmit with a half-skip off the outer wall, receive
directly, both legs shear. It is also why <span class="n">0&deg;</span> is excluded from every
comparison here &mdash; at normal incidence there is no mode conversion, so the wave the
imaging code looks for was never launched, and both solvers produce meaningless images.</p>
</div>

<figure>
  <img src="{img['gif']}" alt="Animated wavefield: the steered beam converting to shear">
  <figcaption><b>The mechanism, in our simulation.</b> Water carries no shear, so the two wave
  types can be shown together without ambiguity: compression (<code>div u</code>) in the water,
  shear (<code>curl u</code>) in the steel. The steered wavefront sweeps in, converts at the
  inner wall, and the shear wave zig-zags through the wall on the half-skip path toward the
  notch at <span class="n">x = 38.25</span> mm. Illustrative resolution; every quoted number
  comes from the higher-resolution runs.</figcaption>
</figure>

<h2 class="col"><span class="num">03</span>Two ways to simulate a wave</h2>
<div class="col">
<p>Both models solve the same elastic wave equation. They disagree about how to represent
<em>space</em>, and that is the whole story.</p>
<h3>k-Wave: a uniform grid</h3>
<p>k-Wave is <strong>pseudospectral</strong> on a uniform Cartesian grid &mdash;
<span class="n">50</span> &micro;m squares here. In smooth material it is genuinely excellent:
derivatives come from Fourier transforms, which is very accurate per point. The cost is that
geometry has to be painted onto that grid. A curved wall becomes a <strong>staircase</strong>;
a crack becomes a block of pixels. And because a finite-difference grid cannot contain a hole,
the crack must be filled with <em>something</em> &mdash; k-Wave fills it with a fictitious
solid at <span class="n">500</span> m/s.</p>
<h3>FEniCS/DOLFINx: a mesh that follows the geometry</h3>
<p>We use the <strong>finite element method</strong>, which divides the domain into cells of
any shape. The pipe's surfaces are meshed as <em>exact circular arcs</em>, and the notch is cut
as real geometry &mdash; a true void whose faces are mesh boundaries. A void needs no fake
material: the natural boundary condition of the equations on a free surface is exactly
traction-free, which is what steel against air is.</p>
<p>Measured, the fidelity gap is large. Our meshed arcs deviate from the true circle by
<strong><span class="n">0.05</span> &micro;m</strong>, against roughly
<span class="n">140</span> &micro;m for a staircase at the same cell size. Whether that
fidelity is <em>why</em> we win is a different question, and section 09 answers it
uncomfortably.</p>
</div>

<figure>
  <img src="{img['mesh']}" alt="Mesh zooms: conforming arc, 50 micron staircase, notch tip">
  <figcaption><b>What "conforming" means, drawn from the real meshes.</b> Blue is the interface
  the mesh actually has; dashed green is the exact circle. Panels 2 and 3 use the <em>same</em>
  window, deliberately off-axis where the wall is steep &mdash; at the arc's apex a
  <span class="n">50</span> &micro;m staircase runs flat for <span class="n">&plusmn;3.1</span>
  mm and would look harmless. Panel 4 is the notch tip: a real void with exact
  corners.</figcaption>
</figure>

<div class="col">
<h3>The price of an explicit solver</h3>
<p>We step forward in time explicitly &mdash; cheap per step, but conditionally stable: the
step is limited by the <em>smallest cell divided by the fastest wave speed</em>, globally. That
one sentence explains most of the engineering here, including a costly mistake. Refining the
mesh at the crack tip once cost a factor of ten in runtime for no accuracy gain, because those
tiny cells set the time step for the entire domain.</p>
<p>The alternative to refining is raising the <strong>polynomial degree</strong> inside each
cell, with nodes placed at Gauss&ndash;Lobatto&ndash;Legendre points. Numerical dispersion
&mdash; the error that makes different frequencies travel at slightly wrong speeds, which is
<em>timing</em> error &mdash; falls very fast with degree. Measured on one fixed mesh, timing
error fell from <span class="n">2.19%</span> at degree 1 to <span class="n">0.001%</span> at
degree 4.</p>
</div>

<h2 class="col"><span class="num">04</span>The one decision that makes the comparison fair</h2>
<div class="col">
<p>A simulation is not an image. Turning channel data into a picture takes a beamformer, and
beamformers embed dozens of choices &mdash; travel-time models, filters, apodisation, angle
gating. If we wrote our own, any difference between the two images could be blamed on it.</p>
<p>So we did not. We run <strong>the research team's own beamformer</strong>, unmodified, on
both datasets, loaded in place from a read-only checkout of their repository. Every image on
this page, theirs and ours, comes out of that same code.</p>
<p>That is what makes the rest of this document mean anything: <strong>the forward solver is
the only difference</strong>. The plumbing was verified first by feeding their beamformer their
own data and reproducing their archived image &mdash; identical grid, peak in the identical
pixel, amplitude within <span class="n">2.4%</span>.</p>
<p>One declared substitution: their receive-side travel-time routine refuses to run without
CUDA, so we use the CPU routine from the same package. It applies identically to both datasets,
so it cancels out of the comparison.</p>
</div>

<h2 class="col"><span class="num">05</span>Does our physics work? Four exact tests</h2>
<div class="col">
<p>Before comparing anything to k-Wave, the solver was checked against problems with known
closed-form answers. This is what makes the result a measurement rather than an opinion &mdash;
and notably, the reference work contains no equivalent study.</p>
</div>
<div class="tw col">
<table>
<caption>Validation against exact solutions &mdash; no fitted parameters anywhere</caption>
<thead><tr><th>Test</th><th>What it proves</th><th class="num">Error</th></tr></thead>
<tbody>
<tr><td>Wave speeds in steel</td><td>the constitutive law, both wave types</td>
    <td class="num">0.002% / 0.000%</td></tr>
<tr><td>Water/steel reflection, normal incidence</td><td>fluid&ndash;solid coupling</td>
    <td class="num">0.00%</td></tr>
<tr><td>Mode conversion at 20&deg;</td><td>the physics the whole method depends on</td>
    <td class="num">0.81%</td></tr>
<tr><td>Scattering from a cavity</td><td>a defect scatters right, not just flat walls</td>
    <td class="num">~1%</td></tr>
</tbody>
</table>
</div>
<figure>
  <img src="{img['zoep']}" alt="Mode conversion versus the exact fluid-solid solution">
  <figcaption><b>Mode conversion against the exact solution, 0&ndash;60&deg;.</b> At the
  production angle the converted shear amplitude is within <span class="n">0.81%</span> and the
  shear angle within <span class="n">0.55&deg;</span> of Snell. The apparent outliers near
  <span class="n">15&deg;</span> and <span class="n">30&deg;</span> are not solver error &mdash;
  they sit on the compression-critical and leaky-Rayleigh angles, where a plane-wave
  coefficient is the wrong yardstick for a finite beam. There the simulation is closer to the
  correct beam-averaged answer than the textbook curve.</figcaption>
</figure>
<figure>
  <img src="{img['pao']}" alt="Cavity scattering versus the exact Pao and Mow series">
  <figcaption><b>Scattering from a defect, against the exact Pao &amp; Mow series.</b> Complex
  gain is unity to <span class="n">0.5%</span> in amplitude and <span class="n">0.2&deg;</span>
  in phase, with zero adjustable parameters. This is the check that breaks if the constitutive
  law or the mode conversion is wrong.</figcaption>
</figure>

<h2 class="col"><span class="num">06</span>The head-to-head result</h2>
<div class="col">
<p>Same scenario, same imaging code, both usable angles. Blue is ours, rust is k-Wave's; the
highlighted value in each pair is the more accurate one.</p>
</div>
<div class="tw">
<table>
<caption>TT-T imaging metrics &mdash; identical beamformer, forward solver the only difference</caption>
<thead><tr>
  <th>Metric (true value)</th><th class="num">k-Wave +20&deg;</th><th class="num">FEM +20&deg;</th>
  <th class="num">k-Wave &minus;20&deg;</th><th class="num">FEM &minus;20&deg;</th></tr></thead>
<tbody>
<tr><td class="row-label">Crack position error (38.25 mm)</td>
  <td class="num">0.413 mm</td><td class="num fem">0.165 mm</td>
  <td class="num">0.332 mm</td><td class="num fem">0.084 mm</td></tr>
<tr><td class="row-label">Imaged notch extent (4.0 mm)</td>
  <td class="num">3.23 (&minus;19%)</td><td class="num fem">3.73 (&minus;6.8%)</td>
  <td class="num">6.33 (+58%)</td><td class="num fem">3.85 (&minus;3.8%)</td></tr>
<tr><td class="row-label">Crack / clutter, RMS</td>
  <td class="num">22.8 dB</td><td class="num fem">24.0 dB</td>
  <td class="num">23.1 dB</td><td class="num fem">24.0 dB</td></tr>
<tr><td class="row-label">Crack / clutter, 95th percentile</td>
  <td class="num">16.6 dB</td><td class="num fem">17.0 dB</td>
  <td class="num kw">17.0 dB</td><td class="num tie">16.9 dB &mdash; tie</td></tr>
<tr><td class="row-label">Crack / worst clutter</td>
  <td class="num">10.3 dB</td><td class="num fem">12.2 dB</td>
  <td class="num">9.8 dB</td><td class="num fem">10.4 dB</td></tr>
</tbody>
</table>
</div>
<div class="col">
<p>Nine of ten cells favour us. The tenth is a tie we are not dressing up: at
<span class="n">&minus;20&deg;</span> our 95th-percentile contrast is
<span class="n">0.1</span> dB behind theirs.</p>
<p>A single brightness threshold can flatter anybody, so every geometric claim was re-measured
across every reasonable analysis choice &mdash; six thresholds, four region widths, five
clutter guard distances. <strong>We are closer to truth in 29 of 30.</strong></p>
</div>
<figure>
  <img src="{img['p20']}" alt="k-Wave, FEM, and a defect-free FEM wall at +20 degrees">
  <figcaption><b>+20&deg;, three panels:</b> k-Wave, ours, and ours with the crack removed
  entirely. Each panel is scaled to its own maximum, because the two solvers drive different
  source amplitudes &mdash; only ratios <em>within</em> an image are comparable. Both real
  images carry wall clutter of similar character; that similarity is reassuring for validity
  and is not a win for either side.</figcaption>
</figure>
<figure>
  <img src="{img['m20']}" alt="k-Wave versus FEM at minus 20 degrees">
  <figcaption><b>&minus;20&deg;.</b> The second angle, and the one that mattered most &mdash;
  section 08 explains why these numbers were written down <em>before</em> the solve
  finished.</figcaption>
</figure>

<div class="verdict col">
  <span class="kicker">The result we would lead with</span>
  <p>Our sizing barely moves with steering angle and theirs changes by a factor of two:
  <span class="n">3.73</span> and <span class="n">3.85</span> mm against their
  <span class="n">3.23</span> and <span class="n">6.33</span> mm &mdash; a
  <strong><span class="n">3%</span> spread against <span class="n">96%</span></strong>. Both
  datasets pass through the same imaging chain, so an imaging quirk would move both equally.
  This asymmetry is in their forward model, and the notch is on-axis with symmetric geometry,
  so nothing in the scenario produces it.</p>
  <p>For an inspection tool this matters more than any decibel figure. A real crack is never
  conveniently on-axis, and a sizing error that swings with beam angle is one you cannot
  calibrate away.</p>
</div>

<h2 class="col"><span class="num">07</span>Proving the bright spot is the crack</h2>
<div class="col">
<p>A bright patch in the right place is not proof. So we simulated the identical wall with
<strong>no crack at all</strong>, and imaged it the same way.</p>
<p>In that defect-free run the notch location peaks <span class="n">6.1</span> dB
<em>below</em> the worst clutter elsewhere in the wall &mdash; there is no feature there at
all. The cracked run's response at the same place is <span class="n">16.24</span> dB above it.
Subtracting the two channel-data records cancels the wall coherently and leaves a compact
feature at <span class="n">x = 38.09</span> mm, extent <span class="n">3.85</span> mm,
contrast <span class="n">26.3</span> dB.</p>
<p>The honest limit: removing the notch also removes the mesh cells around it, which changes
the stable time step, so the two runs reach the common sample grid from different step sizes.
The residual floor is <span class="n">2.3%</span> of the difference peak, leaving about
<span class="n">13</span> dB of headroom. Real cancellation, not an exact null.</p>
</div>
<figure>
  <img src="{img['base']}" alt="Cracked, healthy, and difference images">
  <figcaption><b>Crack minus healthy.</b> The wall is common to both runs and cancels; what
  survives is the defect. Shared colour scale across all three panels.</figcaption>
</figure>

<h2 class="col"><span class="num">08</span>The mechanism &mdash; and a correction</h2>
<div class="col">
<p>Our first attempt <em>lost</em> to k-Wave. Why turned out to be the most useful lesson of
the project, and stating it precisely forces a correction to something we claimed earlier.</p>
<h3>Resolution must be sized for bandwidth, not centre frequency</h3>
<p>A mesh built for "four nodes per wavelength at 4 MHz" sounds adequate and is not. A
single-cycle pulse carries roughly <span class="n">100%</span> bandwidth &mdash; real energy
out to <span class="n">6&ndash;8</span> MHz &mdash; and at those frequencies the same mesh has
barely half the nodes it needs. The mesh then low-passes our own pulse as it travels, and
because <strong>axial resolution is set by bandwidth, not centre frequency</strong>, that
single oversight explained every symptom at once: a notch smeared to
<span class="n">8.07</span> mm, a weak crack response, and poor contrast.</p>
<p>Raising the element degree and refining fixed it. Two other explanations were eliminated by
measurement first &mdash; the source pulse (measured <span class="n">5.5</span> MHz wide, so
never the limit) and the absorbing boundary.</p>
</div>
<figure>
  <img src="{img['bw']}" alt="Returned pulse spectra and image metrics versus refinement">
  <figcaption><b>Left:</b> the returned pulse's spectrum, computed from the channel data
  itself. Each refinement recovers more of the <span class="n">4&ndash;6</span> MHz band.
  <b>Right:</b> as that band returns, both image metrics move &mdash; sizing toward the true
  <span class="n">4.0</span> mm, contrast past k-Wave's. <b>Now look at the black
  curve.</b></figcaption>
</figure>
<div class="verdict warn col">
  <span class="kicker">Correction to an earlier claim</span>
  <p>We had been saying "we win because we resolve the bandwidth". That is <strong>wrong as an
  explanation for beating k-Wave</strong>. Their returned pulse is <em>broader</em> than ours
  &mdash; <span class="n">4.17</span> MHz against our <span class="n">3.33</span> &mdash; and
  they still size the notch worse. On that axis they are ahead of us.</p>
  <p>So bandwidth is the mechanism behind <em>our own</em> convergence &mdash; degree 3 loses at
  both angles, degree 4 on a finer mesh wins at both, exactly as predicted. It is not by itself an
  account of the margin over them, and the next section measures how much of that margin each of
  k-Wave's two geometry approximations can account for.</p>
</div>
<div class="col">
<h3>The prediction that makes the mechanism credible</h3>
<p>The bandwidth story was discovered at <span class="n">+20&deg;</span>. Before solving
<span class="n">&minus;20&deg;</span> we wrote down what it had to produce for the mechanism to
be real rather than fitted: contrast <span class="n">23&ndash;25</span> dB, extent
<span class="n">3.7&ndash;4.2</span> mm &mdash; and stated that a materially worse result would
mean reporting the win as one angle only. It came back at <strong><span class="n">24.0</span>
dB and <span class="n">3.85</span> mm</strong>, both inside the range. That is the difference
between an explanation and a story.</p>
</div>

<h2 class="col"><span class="num">09</span>Two experiments to explain the win &mdash; the first failed</h2>
<div class="col">
<p>If our geometry is so much more faithful, that should be measurable. So we tested it
directly, inside our own solver, changing exactly one thing.</p>
<h3>C4: staircase the interface, keep everything else</h3>
<p>A defect-free wall, run twice: once with the inner surface as an exact arc, once as a
<span class="n">50</span> &micro;m pixel staircase &mdash; k-Wave's own grid spacing. Same
solver, same cell sizes, same source, same imaging. A defect-free wall must image black, so
everything in the picture is numerical.</p>
</div>
<div class="tw col">
<table>
<caption>C4: staircased versus conforming inner wall, healthy pipe, +20&deg;</caption>
<thead><tr><th>Wall clutter</th><th class="num">Conforming</th><th class="num">Staircased</th>
  <th class="num">Difference</th></tr></thead>
<tbody>
<tr><td class="row-label">RMS</td><td class="num">0.02967</td><td class="num">0.03183</td>
  <td class="num">+0.61 dB</td></tr>
<tr><td class="row-label">95th percentile</td><td class="num">0.05708</td>
  <td class="num">0.06327</td><td class="num">+0.89 dB</td></tr>
<tr><td class="row-label">Worst pixel</td><td class="num">0.1083</td><td class="num">0.1228</td>
  <td class="num">+1.09 dB</td></tr>
<tr><td class="row-label">Steps for the same 60 &micro;s</td><td class="num">51,748</td>
  <td class="num">364,157</td><td class="num">7.0&times;</td></tr>
</tbody>
</table>
</div>
<figure>
  <img src="{img['c4']}" alt="Conforming versus staircased inner wall - indistinguishable">
  <figcaption><b>The experiment that failed, on a shared colour scale.</b> These two panels are
  supposed to look different. They do not. Staircasing the curved interface at k-Wave's own grid
  spacing moves the numerical clutter floor by at most about <span class="n">1</span> dB
  &mdash; consistent in direction across all three measures, and far too small to explain a
  <span class="n">1.2</span> dB advantage.</figcaption>
</figure>
<div class="verdict dead col">
  <span class="kicker">Measured, bounded, and withdrawn from the claims</span>
  <p>This project had asserted since its design phase that our advantage came from conforming
  geometry. Having now measured it at <strong>0.61 dB</strong>, that claim is
  <strong>withdrawn</strong> and appears nowhere in our results. Quantifying a candidate and
  ruling it out is what keeps the surviving claims defensible.</p>
  <p>One genuine finding survives, valid inside FEM only: staircasing forced
  <span class="n">7&times;</span> more time steps for the same simulated time <em>and</em> was
  slightly worse. That argues for conforming meshes on cost grounds. It is not a comparison
  with k-Wave, whose uniform grid has a different stability limit.</p>
</div>
<div class="col">
<h3>C5: the crack void &mdash; the remaining candidate</h3>
<p>k-Wave cannot leave a hole in its grid, so it fills the crack with a fictitious material:
compression speed <span class="n">500</span> m/s, shear speed <span class="n">0</span>, density
<span class="n">500</span> &mdash; read from their script, not guessed. At 4 MHz that material
has a <span class="n">0.125</span> mm wavelength, which their grid resolves with only
<span class="n">2.5</span> points. That is a far cruder approximation than staircasing a smooth
arc, and C4 could not see it, because C4 had no crack.</p>
<p>So we built the same conforming notch twice: once as a traction-free void, once filled with
their material at a deliberately matched <span class="n">2.08</span> nodes per wavelength.
Identical time step, identical step count, 88 extra cells. One variable.</p>
<p><strong>Prediction, on record before the result:</strong> a small effect &mdash; under
<span class="n">1</span> dB and under <span class="n">0.3</span> mm of sizing change. A filled
crack still reflects <span class="n">98.9%</span> of the amplitude a true free surface would,
so barely any energy enters it to be got wrong. If that holds, then neither of k-Wave's
geometry approximations explains our advantage, and the honest position is
<em>"we measure better and cannot yet attribute it"</em> &mdash; which is a legitimate
scientific state, and better than picking a story.</p>
</div>
{c5_block}

<h2 class="col"><span class="num">10</span>What we cannot claim</h2>
<div class="ledger col">
  <div class="claim"><span class="tag yes">Solid</span><div>
    <p>More accurate crack sizing than k-Wave at both usable angles.</p>
    <p>Unanimous across analysis choices, and converged: 8.07 &rarr; 3.85 &rarr; 3.73 mm, the
    last refinement moving it 0.12 mm.</p></div></div>
  <div class="claim"><span class="tag yes">Solid</span><div>
    <p>Angle consistency &mdash; 3% spread against their 96%.</p>
    <p>Shared imaging chain, so it is attributable to the forward model.</p></div></div>
  <div class="claim"><span class="tag yes">Solid</span><div>
    <p>The physics is right to about 1%.</p>
    <p>Four exact-solution tests, no fitted parameters. The reference work has no
    equivalent.</p></div></div>
  <div class="claim"><span class="tag part">Bounded</span><div>
    <p>Contrast advantage of +1.2 dB.</p>
    <p>A <b>lower bound only</b> &mdash; still improving at our last refinement, so the
    converged value is unknown. No Richardson error bars computed.</p></div></div>
  <div class="claim"><span class="tag part">Bounded</span><div>
    <p>Better crack localisation.</p>
    <p>Quote as <b>sub-pixel, &le;0.25 mm</b>, never as a ratio. Our own value moved 0.24 mm
    between meshes &mdash; about one image pixel, comparable to the whole claimed
    advantage.</p></div></div>
  <div class="claim"><span class="tag part">Quantified</span><div>
    <p>How much each of k-Wave's geometry approximations costs.</p>
    <p>Staircasing measured at <b>0.61 dB</b>, the crack fill at <b>0.07 dB</b> &mdash; both too
    small to account for the margin, so neither is offered as its explanation. A third candidate,
    interface sharpness, is under test with its prediction on record.</p></div></div>
  <div class="claim"><span class="tag dead">Withdrawn</span><div>
    <p>"We win because the mesh conforms to the geometry."</p>
    <p>Measured at &le;1 dB by our own controlled experiment. Not used anywhere.</p></div></div>
  <div class="claim"><span class="tag no">Not done</span><div>
    <p>Generalisation beyond this case.</p>
    <p>Two angles, one crack size, one crack shape, <b>2-D only</b>. No defect-free k-Wave run
    exists at these settings, so that comparison is ours alone.</p></div></div>
</div>

<h2 class="col"><span class="num">11</span>Mistakes worth keeping</h2>
<div class="col">
<p>Recorded because each produced a confident, wrong number before being caught, and these
failure modes recur.</p>
<ul>
<li><strong>A delay law off by 1000&times;.</strong> Their ray routine takes millimetres and
returns milliseconds. Caught by comparing against their own recorded delays; now asserted on
every run.</li>
<li><strong>The wrong length scale for stability.</strong> Using cell <em>diameter</em> instead
of shortest <em>edge</em> gave a time step that looked fine for a few hundred steps and
diverged thousands later.</li>
<li><strong>Two analysis routines that invented results.</strong> A window-maximum arrival
picker reported an echo where the trace had no peak at all; an onset picker returned the
window's lower bound whenever its threshold was never crossed, manufacturing a fake "perfect
agreement" across half the array.</li>
<li><strong>A figure that measured noise.</strong> The first version of the spectrum plot used
the whole 60 &micro;s record and ranked the coarsest mesh as the <em>widest</em> band &mdash;
backwards. That tail is dominated by dispersion noise, not pulse energy.</li>
<li><strong>Sizing the mesh for centre frequency.</strong> The root cause of the initial loss,
and entirely self-inflicted.</li>
</ul>
</div>

<h2 class="col"><span class="num">12</span>What actually limits the speed</h2>
<div class="col">
<p>Two performance claims were estimated, then measured, and both estimates were wrong. Recording
that here because the corrections are more useful than the original guesses.</p>
<ul>
<li><strong>Parallelism gives 1.71x, not the 4-8x we estimated.</strong> DOLFINx is MPI-parallel
and partitions almost perfectly (imbalance <= 1.02x), but the operation is
<em>memory-bandwidth</em> bound: each step streams ~1.26 GB through a sparse product at ~24 GB/s,
about this machine's limit. Cores share one memory bus, so returns are sublinear by
construction.</li>
<li><strong>A matrix-free prototype came out 10x SLOWER</strong> than the code we already run.
The algorithm is right and is standard for high-order elements, but pure NumPy allocates
~120 MB of temporaries per application. Realising it needs a compiled kernel, which is a much
larger commitment than the earlier estimate implied.</li>
<li><strong>The real headroom is the time step.</strong> Ours comes from a conservative rule of
thumb. Computing the exact stability limit directly - <code>2/sqrt(lambda_max(M<sup>-1</sup>K))</code>
by power iteration - shows our step sits at <strong>16.4% of it</strong>, i.e. roughly
<strong>6x</strong> available. An independent code's published rule agrees with that measurement
to 5%. A first trial at 4x ran stably with peak amplitude unchanged to 0.01%; it needs one
validation pass against known arrival times before being adopted, since a larger step also raises
temporal dispersion, and timing accuracy is the whole point of this simulation.</li>
</ul>
</div>

<h2 class="col"><span class="num">13</span>Slide map</h2>
<div class="col"><p>Suggested deck order. Figures live under
<code>Fea/research/fenics/results/</code>.</p></div>
<div class="slides">
  <div class="slide"><div><b>The inspection problem</b>
    <span>Pipe, wall, a 42%-through-wall crack on the far side. The answer is a time, not a
    brightness. <em>schematic or text</em></span></div></div>
  <div class="slide"><div><b>Why the beam is steered</b>
    <span>Mode conversion, the 15.3&deg; critical angle, pure shear at ~45&deg;, the TT-T path.
    <em>viz/wavefield_snap_p20deg_t27p0us.png</em></span></div></div>
  <div class="slide"><div><b>The wavefield &mdash; play this</b>
    <span>Compression in water, shear in steel, half-skip to the notch.
    <em>viz/wavefield_snap_p20deg.gif</em></span></div></div>
  <div class="slide"><div><b>Grid versus mesh</b>
    <span>Staircase against exact arc; the crack as a void, not fake material.
    <em>viz/mesh_zoom.png</em></span></div></div>
  <div class="slide"><div><b>Making it a fair fight</b>
    <span>Their beamformer on our data, so the forward solver is the only difference;
    round-trip verified to the same pixel. <em>no figure</em></span></div></div>
  <div class="slide"><div><b>Validation against exact solutions</b>
    <span>0.81% mode conversion, ~1% defect scattering, no fitted parameters.
    <em>fluid_solid/mode_conversion.png + cavity_scattering/dscf_vs_exact.png</em></span></div></div>
  <div class="slide"><div><b>Head-to-head</b>
    <span>The two-angle table; 29/30 robustness checks.
    <em>table + compare/compare_p20deg.png</em></span></div></div>
  <div class="slide"><div><b>The result to lead with</b>
    <span>Sizing spread 3% against 96% across angle. <em>two-row table</em></span></div></div>
  <div class="slide"><div><b>The crack is real</b>
    <span>A defect-free wall images empty; the difference isolates the crack.
    <em>compare/baseline_subtract_20deg.png</em></span></div></div>
  <div class="slide"><div><b>Why: bandwidth, with the caveat</b>
    <span>Resolution must follow bandwidth &mdash; and k-Wave is ahead of us on it.
    <em>viz/bandwidth_convergence.png</em></span></div></div>
  <div class="slide"><div><b>Prediction, then test</b>
    <span>&minus;20&deg; numbers written down first; landed inside the range.
    <em>quote the range and the result</em></span></div></div>
  <div class="slide"><div><b>The experiment that failed</b>
    <span>C4: staircasing changes almost nothing; claim withdrawn.
    <em>compare/c4_staircase_vs_conforming.png</em></span></div></div>
  <div class="slide"><div><b>What we cannot claim</b>
    <span>The ledger: lower bounds, sub-pixel, the open question, the withdrawn claim.
    <em>table</em></span></div></div>
</div>

<footer>
  <p>Every figure regenerates from committed code and cached data; nothing is hand-drawn. Full
  record including all traps and withdrawn claims:
  <code>C:/code/readme/rnd-nima-fea-README.md</code>. Reproduction recipe:
  <code>Fea/research/fenics/README.md</code>.</p>
</footer>
"""
